"""
feature_engineering.py
-----------------------
Creates time-series features for ML models (XGBoost, LSTM).

Feature mapping based on W-SAT frequency:
- t-1, t-7 → lag_1 (1 week lag)
- t-30 → lag_4 (4 week lag)
Also includes 4-week rolling stats, date features, and US holiday flags.
"""

import logging
from typing import List

import holidays
import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

_US_HOLIDAYS = holidays.UnitedStates()


def add_holiday_flag(dates: pd.DatetimeIndex) -> np.ndarray:
    """Return a binary array: 1 if date is a US public holiday, else 0."""
    return np.array([1 if d in _US_HOLIDAYS else 0 for d in dates], dtype=np.int8)


def create_features(df: pd.DataFrame, target_col: str = "Total") -> pd.DataFrame:
    """
    Appends lag, rolling, date, and holiday features. 
    Drops NaN rows generated by rolling windows.
    """
    df = df.copy()
    s = df[target_col]

    # Lag features (t-1/t-7 -> lag_1, t-30 -> lag_4)
    df["lag_1"] = s.shift(1)
    df["lag_4"] = s.shift(4)

    # Rolling statistics
    df["rolling_mean_4"] = s.shift(1).rolling(window=4).mean()
    df["rolling_std_4"]  = s.shift(1).rolling(window=4).std()

    # Date and holiday features
    df["day_of_week"]  = df.index.dayofweek
    df["month"]        = df.index.month
    df["quarter"]      = df.index.quarter
    df["week_of_year"] = df.index.isocalendar().week.astype(int)
    df["is_holiday"] = add_holiday_flag(df.index)

    # Drop NaN rows created by lags/rolling
    before = len(df)
    df.dropna(inplace=True)
    logger.debug(f"Feature engineering: dropped {before - len(df)} NaN rows "
                 f"(lag/rolling window), {len(df)} rows remaining.")
    return df


def get_feature_columns() -> List[str]:
    """Returns the ordered list of ML feature columns."""
    return [
        "lag_1", "lag_4",
        "rolling_mean_4", "rolling_std_4",
        "day_of_week", "month", "quarter", "week_of_year",
        "is_holiday",
    ]


def train_val_test_split(
    df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Strict time-based split (No shuffling) to prevent data leakage.
    Train: < 2023-01-01 | Val: 2023-01-01 to 2023-06-30 | Test: >= 2023-07-01
    """
    train = df[df.index < "2023-01-01"]
    val   = df[(df.index >= "2023-01-01") & (df.index < "2023-07-01")]
    test  = df[(df.index >= "2023-07-01") & (df.index <= "2023-12-31")]
    return train, val, test


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(__import__("pathlib").Path(__file__).parents[1]))
    logging.basicConfig(level=logging.DEBUG)
    from src.preprocessing import load_and_preprocess

    state_data = load_and_preprocess()
    state, raw_df = next(iter(state_data.items()))
    feat_df = create_features(raw_df)
    print(f"\n{state} — feature columns:\n{feat_df.head()}")
    tr, va, te = train_val_test_split(feat_df)
    print(f"Train: {len(tr)}, Val: {len(va)}, Test: {len(te)}")
